# Generated by Django 4.2.6 on 2023-12-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(max_length=25)),
                ('user_image', models.TextField()),
                ('user_login', models.SmallIntegerField()),
                ('exmacredits', models.IntegerField(default=7)),
            ],
        ),
    ]
