# Generated by Django 4.2.6 on 2023-12-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0003_questions_alter_users_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
