# Generated by Django 4.2.6 on 2023-12-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0004_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('questions_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_id', models.CharField(max_length=100)),
                ('qid', models.CharField(max_length=25)),
                ('q', models.TextField()),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
