# Generated by Django 4.2.6 on 2023-12-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0005_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=75)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('show_ans', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('proctoring_type', models.SmallIntegerField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
