# Generated by Django 4.2.6 on 2023-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0006_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='studenttestinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('time_left', models.TimeField()),
                ('completed', models.SmallIntegerField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
