# Generated by Django 4.2.6 on 2023-12-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0007_studenttestinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studenttestinfo',
        ),
    ]
