# Generated by Django 4.2.6 on 2023-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0008_delete_studenttestinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='studenttestinfo',
            fields=[
                ('stiid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('time_left', models.TimeField()),
                ('completed', models.SmallIntegerField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
