# Generated by Django 4.2.6 on 2023-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0009_studenttestinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('qid', models.CharField(max_length=25)),
                ('ans', models.TextField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
