# Generated by Django 4.2.6 on 2023-12-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0010_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestinfo',
            name='completed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
