# Generated by Django 4.2.6 on 2023-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0011_alter_studenttestinfo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestinfo',
            name='time_left',
            field=models.IntegerField(),
        ),
    ]
