# Generated by Django 4.2.6 on 2023-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0013_proctoring_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='practicalqa',
            fields=[
                ('pracqa_qid', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_id', models.CharField(max_length=100)),
                ('qid', models.CharField(max_length=25)),
                ('q', models.TextField()),
                ('compiler', models.SmallIntegerField()),
                ('marks', models.IntegerField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
