# Generated by Django 4.2.6 on 2023-12-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishtikon', '0014_practicalqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='practicaltest',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('qid', models.CharField(max_length=25)),
                ('code', models.TextField(blank=True, null=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('executed', models.CharField(max_length=125)),
                ('marks', models.IntegerField()),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
